### ISSUE TITLE
Failed converting ECJ parse tree to PSI for....  IllegalArgumentException: ArrayTypeReference

### ISSUE THREAD

**Issue by Synthlight** [evant/android-retrolambda-lombok#19]
Small snippet that causes the error:
```
public class Test {
    private static class Foo {
        private final String a = "";
    }

    private void fun() {
        List<Foo> fooList = new ArrayList<Foo>() {{
            add(new Foo());
            add(new Foo());
        }};

        String[] strings = Stream.of(fooList)
                .map(foo -> foo.a)
                .toArray(String[]::new);
    }
}
```

Only way I can find to get rid of the error is to change ```.toArray(String[]::new);``` to ```.toArray(value -> new String[value]);```.

```
Failed converting ECJ parse tree to PSI for file /home/gregory/Code/TestTest/app/src/main/java/com/example/gregory/myapplication/Test.java
java.lang.IllegalArgumentException: org.eclipse.jdt.internal.compiler.ast.ArrayTypeReference
	at com.android.tools.lint.psi.EcjPsiBuilder.toExpression(EcjPsiBuilder.java:977)
	at com.android.tools.lint.psi.EcjPsiBuilder.toFunctionalExpression(EcjPsiBuilder.java:1038)
	at com.android.tools.lint.psi.EcjPsiBuilder.toExpression(EcjPsiBuilder.java:969)
	at com.android.tools.lint.psi.EcjPsiBuilder.toArguments(EcjPsiBuilder.java:2281)
	at com.android.tools.lint.psi.EcjPsiBuilder.toCallExpression(EcjPsiBuilder.java:1094)
	at com.android.tools.lint.psi.EcjPsiBuilder.toExpression(EcjPsiBuilder.java:959)
	at com.android.tools.lint.psi.EcjPsiBuilder.toVariable(EcjPsiBuilder.java:1723)
	at com.android.tools.lint.psi.EcjPsiBuilder.toDeclarationStatement(EcjPsiBuilder.java:2376)
	at com.android.tools.lint.psi.EcjPsiBuilder.toStatement(EcjPsiBuilder.java:1852)
	at com.android.tools.lint.psi.EcjPsiBuilder.toBlock(EcjPsiBuilder.java:1811)
	at com.android.tools.lint.psi.EcjPsiBuilder.toMethod(EcjPsiBuilder.java:913)
	at com.android.tools.lint.psi.EcjPsiBuilder.initializeClassBody(EcjPsiBuilder.java:798)
	at com.android.tools.lint.psi.EcjPsiBuilder.toClass(EcjPsiBuilder.java:700)
	at com.android.tools.lint.psi.EcjPsiBuilder.toFile(EcjPsiBuilder.java:2518)
	at com.android.tools.lint.psi.EcjPsiBuilder.create(EcjPsiBuilder.java:387)
	at com.android.tools.lint.EcjParser$EcjResult.findFile(EcjParser.java:348)
	at com.android.tools.lint.EcjParser.parseJavaToPsi(EcjParser.java:634)
	at com.android.tools.lint.client.api.JavaPsiVisitor.visitFile(JavaPsiVisitor.java:277)
	at com.android.tools.lint.client.api.LintDriver.visitJavaFiles(LintDriver.java:1571)
	at com.android.tools.lint.client.api.LintDriver.checkJava(LintDriver.java:1551)
	at com.android.tools.lint.client.api.LintDriver.runFileDetectors(LintDriver.java:1090)
	at com.android.tools.lint.client.api.LintDriver.checkProject(LintDriver.java:935)
	at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:454)
	at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:395)
	at com.android.tools.lint.LintCliClient.run(LintCliClient.java:131)
	at com.android.build.gradle.internal.LintGradleClient.run(LintGradleClient.java:146)
	at com.android.build.gradle.tasks.Lint.runLint(Lint.java:255)
	at com.android.build.gradle.tasks.Lint.lintSingleVariant(Lint.java:224)
	at com.android.build.gradle.tasks.Lint.lint(Lint.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:624)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:607)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:45)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The test proj I used to reproduce this:
[IssueTestProj.zip](https://github.com/evant/android-retrolambda-lombok/files/683176/IssueTestProj.zip)
- Load project
- Change to release (Doesn't happen on debug)
- Build APK

The error won't actually stop the build, everything seems to work anyways but it clutters the log :(

**Comment by themores** [comment]
i get this error the same, do you work now ?
