### ISSUE TITLE
Doesn't seem to correctly use modified lombok version

### ISSUE THREAD

**Issue by hzsweers** [evant/android-retrolambda-lombok#4]
Hooked up everything as specified in the README, but lint still crashes when it encounters Lambda expressions in the AST. My guess is that it's still using the bundled lint version for some reason despite the classpath exclusion. Any ideas?

```
Failed converting ECJ parse tree to Lombok for file <thefile>
java.lang.UnsupportedOperationException: Unknown ASTNode child: LambdaExpression
	at lombok.ast.ecj.EcjTreeVisitor.visitOther(EcjTreeVisitor.java:368)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:364)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
	at lombok.ast.ecj.EcjTreeConverter.access$100(EcjTreeConverter.java:141)
	at lombok.ast.ecj.EcjTreeConverter$2.visitMessageSend(EcjTreeConverter.java:1042)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:156)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
	at lombok.ast.ecj.EcjTreeConverter.toBlock(EcjTreeConverter.java:397)
	at lombok.ast.ecj.EcjTreeConverter.access$1500(EcjTreeConverter.java:141)
	at lombok.ast.ecj.EcjTreeConverter$2.visitBlock(EcjTreeConverter.java:636)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:292)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:229)
	at lombok.ast.ecj.EcjTreeConverter.access$000(EcjTreeConverter.java:141)
	at lombok.ast.ecj.EcjTreeConverter$2.visitTryStatement(EcjTreeConverter.java:1145)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:52)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
	at lombok.ast.ecj.EcjTreeConverter.toBlock(EcjTreeConverter.java:397)
	at lombok.ast.ecj.EcjTreeConverter.access$1500(EcjTreeConverter.java:141)
	at lombok.ast.ecj.EcjTreeConverter$2.visitMethodDeclaration(EcjTreeConverter.java:1241)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:152)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
	at lombok.ast.ecj.EcjTreeConverter.access$100(EcjTreeConverter.java:141)
	at lombok.ast.ecj.EcjTreeConverter$2.createNormalTypeBody(EcjTreeConverter.java:563)
	at lombok.ast.ecj.EcjTreeConverter$2.visitTypeDeclaration(EcjTreeConverter.java:486)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:48)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
	at lombok.ast.ecj.EcjTreeConverter.access$100(EcjTreeConverter.java:141)
	at lombok.ast.ecj.EcjTreeConverter$2.createNormalTypeBody(EcjTreeConverter.java:563)
	at lombok.ast.ecj.EcjTreeConverter$2.visitTypeDeclaration(EcjTreeConverter.java:486)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:48)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
	at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
	at lombok.ast.ecj.EcjTreeConverter.access$100(EcjTreeConverter.java:141)
	at lombok.ast.ecj.EcjTreeConverter$2.visitCompilationUnitDeclaration(EcjTreeConverter.java:441)
	at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:264)
	at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
	at com.android.tools.lint.EcjParser.parseJava(EcjParser.java:411)
	at com.android.tools.lint.client.api.JavaVisitor.visitFile(JavaVisitor.java:236)
	at com.android.tools.lint.client.api.LintDriver.checkJava(LintDriver.java:1491)
	at com.android.tools.lint.client.api.LintDriver.runFileDetectors(LintDriver.java:1026)
	at com.android.tools.lint.client.api.LintDriver.checkProject(LintDriver.java:882)
	at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:433)
	at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:374)
	at com.android.tools.lint.LintCliClient.run(LintCliClient.java:129)
	at com.android.build.gradle.internal.LintGradleClient.run(LintGradleClient.java:112)
	at com.android.build.gradle.internal.LintGradleClient$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.android.build.gradle.tasks.Lint.runLint(Lint.groovy:198)
	at com.android.build.gradle.tasks.Lint.this$4$runLint(Lint.groovy)
	at com.android.build.gradle.tasks.Lint$this$4$runLint$1.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at com.android.build.gradle.tasks.Lint.lintSingleVariant(Lint.groovy:173)
	at com.android.build.gradle.tasks.Lint$lintSingleVariant$0.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
	at com.android.build.gradle.tasks.Lint.lint(Lint.groovy:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by evant** [comment]
You can use
```groovy
task printBuildScriptClasspath << {
    println project.buildscript.configurations.classpath.asPath
}
```
to print out the classpath and ensure it's not there.

**Comment by hzsweers** [comment]
Hmmm, seems it is using the correct one then. I'm not sure now what the problem could be then. Any ideas?

**Comment by evant** [comment]
I'd need more info, like your `build.gradle` files(s). Are you sure that you aren't missing applying it to a module?

**Comment by hzsweers** [comment]
I was wondering about that actually. The README doesn't specify an `apply ______` line, so I don't have one. I wasn't sure if it was just a matter of having it on the classpath. Is there anything else?

Otherwise, I can't share this build script exactly, but I can see if I can put up a sample project.

**Comment by evant** [comment]
Yeah, classpath is all you need, it's replacing a dependency of the android gradle plugin, it's not a plugin itself. You just need to make sure it's on the classpath and the original one is _not_ on the classpath. A sample project would be great!

**Comment by hzsweers** [comment]
So I haven't been able to put together a sample project that exhibits this, but now I've started running to an entirely separate issue when I try the main project again.

```
An exception has occurred in the compiler (1.8.0_25). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
```

Seems related to https://github.com/evant/gradle-retrolambda/issues/23 and https://github.com/evant/gradle-retrolambda/issues/86, but I'm using v3.1 and android gradle plugin 1.2.2. Should I open a separate issue in the gradle-retrolambda?

**Comment by hzsweers** [comment]
Ok, still happening with the main app. Going to try posting a skimmed down `build.gradle`

```groovy
// This is the app module build.gradle, there are other things added to the classpath in the top level buildscript as well
buildscript {
    repositories {
        mavenCentral()
        maven {
            url  "http://dl.bintray.com/evant/maven"
        }
    }

    dependencies {
        // this needs to be in the same gradle file as where we apply the spoon plugin
        classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.0.2'
        classpath 'me.tatarka:gradle-retrolambda:3.1.0'
        classpath 'me.tatarka.retrolambda.projectlombok:lombok.ast:0.2.3.a1'
    }
    configurations.classpath.exclude group: 'com.android.tools.external.lombok'
}

apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'io.fabric'
apply plugin: 'de.undercouch.download'
apply plugin: 'play'
apply plugin: 'de.felixschulze.gradle.hockeyapp'
apply plugin: 'org.kordamp.markdown.convert'
apply plugin: 'checkstyle'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'spoon'
apply plugin: 'aar-link-sources'

ext {
    // some stuff
}

spoon {
    debug = true
}

android {
    compileSdkVersion COMPILE_SDK_VERSION.toInteger()
    buildToolsVersion BUILD_TOOLS_VERSION

    packagingOptions {
        // these are duplicated in the jackson libraries
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        // for Espresso
        exclude 'LICENSE.txt'
    }

    defaultConfig {
        versionCode VERSION_CODE.toInteger()
        versionName VERSION_NAME

        minSdkVersion 14
        targetSdkVersion 18
        applicationId "app.id"

        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-project.txt'

        multiDexEnabled true

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        renderscriptTargetApi LATEST_TARGET_SDK.toInteger()
        renderscriptSupportModeEnabled true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
    dexOptions {
        javaMaxHeapSize "2g"
        preDexLibraries = !project.getGradle().startParameter.taskNames.any{it.contains('Jenkins')} // We want to disable these for jenkins builds
    }

    signingConfigs {
        debug {
            // stuff
        }
        release {
            // stuff
        }
    }

    buildTypes {
        // Stuff
    }

    productFlavors {
        // Stuff
    }

    applicationVariants.all { variant ->
    	// Stuff
    }

    lintOptions {
        abortOnError true
        check 'NewApi', 'InlinedApi'
        fatal 'NewApi', 'InlinedApi'
        enable 'UnusedResources'
        htmlReport true
        htmlOutput file("lint-report.html")
        checkReleaseBuilds true
        textReport true
        textOutput 'lint_result.txt'
    }
}

retrolambda {
    jdk System.getenv("JAVA8_HOME")
    oldJdk System.getenv("JAVA7_HOME")
    javaVersion JavaVersion.VERSION_1_7
    defaultMethods false
    incremental true
}

play {
    // Stuff
}

hockeyapp {
    // Stuff
}

markdownToHtml {
    // Stuff
}

// Some custom tasks

// Gradle's default is 5.7, which doesn't support Java 8 features
checkstyle {
    toolVersion = "6.6"
}
task checkstyle(type: Checkstyle) {
    source 'src'
    include '**/*.java'
    exclude '**/gen/**'
    exclude '**/R.java'
    exclude '**/BuildConfig.java'

    configFile new File(projectDir, "checkstyle.xml")

    // empty classpath
    classpath = files()
}

dependencies {
    // Stuff
}
```

**Comment by evant** [comment]
> This is the app module build.gradle, there are other things added to the classpath in the top level buildscript as well

What's added in the top-level buildscript, are you adding the exclude line there as well?

**Comment by hzsweers** [comment]
So that seemed to help, but now we get different lombok errors during linting:

```
Failed converting ECJ parse tree to Lombok for file <the file>
java.lang.ClassCastException: lombok.ast.Block cannot be cast to lombok.ast.Expression
```

**Comment by hzsweers** [comment]
Nevermind, updated to 2a and now it works!

**Comment by zouyongdang** [comment]
So what's the solution? I ran into shi error as well.
My gradle file:
```
buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
        classpath 'me.tatarka:gradle-retrolambda:2.5.0'
        classpath 'io.fabric.tools:gradle:1.19.1'
        classpath 'me.tatarka.retrolambda.projectlombok:lombok.ast:0.2.3.a2'
    }
    configurations.classpath.exclude group: 'com.android.tools.external.lombok'
}

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'me.tatarka.retrolambda'

android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    compileSdkVersion 22
    buildToolsVersion "20.0.0"

    defaultConfig {
        applicationId "my.package.id"
        minSdkVersion 14
        targetSdkVersion 22
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            signingConfig signingConfigs.release
        }
    }
}

repositories {
    maven { url 'http://clinker.47deg.com/nexus/content/groups/public' }
    maven { url 'https://maven.fabric.io/public' }
    maven { url = "https://oss.sonatype.org/content/repositories/snapshots" }
}

dependencies {
    //My dependencies
}

apt {
    arguments {
        resourcePackageName android.defaultConfig.applicationId
        androidManifestFile variant.outputs[0].processResources.manifestFile
    }
}
```

**Comment by gregbacchus** [comment]
@zouyongdang If you haven't got a solution yet, see http://stackoverflow.com/a/30536556/48225

It seems, you need to put the `buildscript` section in you **project** build.gradle file, not the **module** build.gradle
