### ISSUE TITLE
java.lang.ClassCastException: lombok.ast.Block cannot be cast to lombok.ast.Expression

### ISSUE THREAD

**Issue by PietroDev** [evant/android-retrolambda-lombok#5]
I tried it with latest versione of lini (24.2.2, but also on 24.1.0) and I obtain:

```java
java.lang.ClassCastException: lombok.ast.Block cannot be cast to lombok.ast.Expression
at lombok.ast.ecj.EcjTreeConverter$2.visitReturnStatement(EcjTreeConverter.java:1181)
at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:96)
at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:206)
at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:147)
at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:193)
at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:163)
at lombok.ast.ecj.EcjTreeConverter.toBlock(EcjTreeConverter.java:308)
at lombok.ast.ecj.EcjTreeConverter.access$1500(EcjTreeConverter.java:52)
at lombok.ast.ecj.EcjTreeConverter$2.visitSwitchStatement(EcjTreeConverter.java:1030)
at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:72)
at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:206)
at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:147)
at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:193)
at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:163)
at lombok.ast.ecj.EcjTreeConverter.toBlock(EcjTreeConverter.java:308)
at lombok.ast.ecj.EcjTreeConverter.access$1500(EcjTreeConverter.java:52)
at lombok.ast.ecj.EcjTreeConverter$2.visitMethodDeclaration(EcjTreeConverter.java:1152)
```

**Comment by evant** [comment]
It didn't like the lambda block syntax. I created a new LambdaExpression node to wrap the body and that seems to have fixed it.

**Comment by PietroDev** [comment]
It works now. Thanks.
